version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  verbosity: minimal
test: off
deploy:
    provider: Environment
    name: TeamOmlet
    on:
      branch: master